### ISSUE TITLE
Obselete in TYPO3 v12

### ISSUE THREAD

**Issue by christophlehmann** [plan2net/single-site#1]
Just FYI. It becomes obselete when https://review.typo3.org/c/Packages/TYPO3.CMS/+/78024/ gets merged.

**Comment by wazum** [comment]
@christophlehmann It doesn't look like that's going to happen, what do you think?  https://review.typo3.org/c/Packages/TYPO3.CMS/+/78024

**Comment by christophlehmann** [comment]
I think so too.
